### ISSUE TITLE
Consul service check fails with TTL expired on Kubernetes

### ISSUE THREAD

**Issue by cantte** [micronaut-projects/micronaut-discovery-client#343]
### Issue description

I am trying to mount this example on a kubernetes cluster 'https://guides.micronaut.io/latest/micronaut-microservices-services-discover-consul-gradle-kotlin.html'. Try to mount the 'bookcatalogue' service on the cluster first, do the configuration with the consul server. Fortunately, the service registers correctly, but after a few seconds the health check fails. as seen in the following image:

![chekc-fails](https://user-images.githubusercontent.com/31832701/162585150-6c62019e-bdc9-494f-a6d7-83f1ccdea523.png)

The problem does not occur when I run the application locally or even when I use docker-compose.
The logs of the kubernetes cluster of the 'bookcatalogue' service are:
```
[36m17:30:46.437[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Established active environments: [k8s, cloud]
[36m17:30:46.447[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Established active environments: [k8s, cloud]
[36m17:30:46.650[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mi.m.context.DefaultBeanContext[0;39m - Reading bootstrap environment configuration
[36m17:30:55.257[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Startup completed in 11295ms. Server Running: http://bookcatalogue-74f7958b5-5gp7d:8080
[36m17:30:57.556[0;39m [1;30m[default-nioEventLoopGroup-1-2][0;39m [34mINFO [0;39m [35mi.m.d.registration.AutoRegistration[0;39m - Registered service [bookcatalogue] with Consul
```

In the consul-server logs I get the following:
```
2022-04-09T17:37:27.289Z [INFO] agent.http: Request cancelled: method=GET url=/v1/health/service/bookcatalogue?dc=dc1&index=3889 from=127.0.0.1:47192 error="context canceled"
2022-04-09T17:38:34.688Z [INFO] agent.http: Request cancelled: method=GET url=/v1/health/service/bookcatalogue?dc=dc1&index=3889 from=127.0.0.1:47262 error="context canceled"
```
I really don't know if I'm configuring consul wrong, this is my config file (I'm running consul with helm -> `helm install -f config.yml consul hashicorp/consul --create-namespace -n consul `
):
config.yml
```
global:
  name: consul
  datacenter: dc1
server:
  replicas: 1
  securityContext:
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0
ui:
  enabled: true
  service:
    type: 'NodePort'
connectInject:
  enabled: true
controller:
  enabled: true
dns:
  enabled: true
  enableRedirection: true
```
And my deployment file for the 'bookcatalogue' service is:
deployment.yml
```
kind: Service
apiVersion: v1
metadata:
  name: bookcatalogue
spec:
  selector:
    app: bookcatalogue
  ports:
    - name: bookcatalogue
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcatalogue
spec:
  selector:
    matchLabels:
      app: bookcatalogue
  template:
    metadata:
      labels:
        app: bookcatalogue
    spec:
      containers:
        - name: bookcatalogue
          image: deworg/bookcatalogue
          env:
            - name: CONSUL_HOST
              value: "consul-server.consul"
            - name: CONSUL_PORT
              value: "8500"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
```

I appreciate any help.

**Comment by cantte** [comment]
Enabling http checking with health endpoint does not cause any problems. At the moment that works for me.
```
consul:
  client:
    registration:
      enabled: true
      prefer-ip-address: true
      health-path: /health
      check:
        interval: 10s
        http: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
    health-check: true
endpoints:
  health:
    enabled: true
    sensitive: false
```
