### ISSUE TITLE
SpringCloud Config Client doesn't work with Micronaut Serialization

### ISSUE THREAD

**Issue by ggerbaud** [micronaut-projects/micronaut-discovery-client#600]
### Expected Behavior

Very similar to #552 

Serializable objects should be annotated with @Serdeable

### Actual Behaviour

ConfigServerResponse and ConfigServerPropertySource classes are not annotated with @Serdeable and then in produce this error 

`Caused by: io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class io.micronaut.discovery.spring.config.client.ConfigServerResponse]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected`

One could use `@SerdeImport(ConfigServerResponse.class)` but `ConfigServerPropertySource` has a protected constructor and then it doesn't work.

### Steps To Reproduce

1. Generate a project with [this configuration](https://micronaut.io/launch?type=DEFAULT&name=demo-scc&package=com.example.scc&javaVersion=JDK_21&lang=JAVA&build=MAVEN&test=JUNIT&features=config-consul&features=yaml&features=http-client&version=4.3.7) (It's for Consul, weirdly there is no SpringCloud Config feature)
2. Remove Consul properties and add these (replace with your SCC instance)
```yml
micronaut:
  application:
    name: demo-scc
  config-client:
    enabled: true
spring:
  cloud:
    config:
      uri: https://my.instance.url
      label: my_label
      username: user
      password: pass
```
3. launch

### Version

4.x
